packages:
  - .
  - demo

overrides:
  launchdarkly-js-client-sdk: link:../js-client-sdk
  launchdarkly-react-client-sdk: link:../react-client-sdk
  - '.'
  - 'demo'

autoInstallPeers: true
strictPeerDependencies: true
