name: Publish Package
description: 'Publish the package to npm'
inputs:
  prerelease:
    description: 'Is this a prerelease. If so, then the latest tag will not be updated in npm.'
    required: false
    default: 'false'
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Publish to npm (dry run)
      if: inputs.dry_run == 'true'
      shell: bash
      run: pnpm --filter @launchdarkly/toolbar publish --dry-run --no-git-checks

    - name: Publish to npm (prerelease)
      if: inputs.dry_run == 'false' && inputs.prerelease == 'true'
      shell: bash
      run: pnpm --filter @launchdarkly/toolbar publish --tag next --no-git-checks

    - name: Publish to npm (release)
      if: inputs.dry_run == 'false' && inputs.prerelease == 'false'
      shell: bash
      run: pnpm --filter @launchdarkly/toolbar publish --no-git-checks
