name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  run_tests:
    description: 'If true, run unit tests, otherwise skip them.'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Lint Code
      shell: bash
      run: pnpm lint

    - name: Build Library
      shell: bash
      id: build
      run: pnpm build

    - name: Run Unit Tests
      if: steps.build.outcome == 'success' && inputs.run_tests == 'true'
      shell: bash
      run: pnpm test
