name: CI Workflow
description: 'Shared CI workflow.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '23'
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Prettier
      shell: bash
      run: pnpm format

    - name: Build Library
      shell: bash
      id: build
      run: pnpm build

    - name: Run Unit Tests
      shell: bash
      run: pnpm test

    - name: Get Playwright Version
      shell: bash
      id: playwright-version
      run: |
        VERSION=$(pnpm list @playwright/test --depth=0 | grep '@playwright/test' | awk '{print $2}')
        if [ -z "$VERSION" ]; then
          VERSION=$(node -e "console.log(require('./node_modules/@playwright/test/package.json').version)")
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Detected Playwright version: $VERSION"

    - name: Cache Playwright Browsers
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Playwright Browsers
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: pnpm exec playwright install --with-deps chromium

    - name: Cache Storybook Build
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: storybook-cache
      with:
        path: storybook-static
        key: storybook-${{ runner.os }}-${{ hashFiles('src/**/*', 'stories/**/*', '.storybook/**/*', 'package.json', 'pnpm-lock.yaml') }}
        restore-keys: |
          storybook-${{ runner.os }}-

    - name: Build Storybook
      shell: bash
      if: steps.storybook-cache.outputs.cache-hit != 'true'
      run: pnpm build:storybook

    - name: Run Playwright Tests
      shell: bash
      run: pnpm test:e2e
