name: CI Workflow
description: 'Shared CI workflow.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '23'
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Prettier
      shell: bash
      run: pnpm format

    - name: Build Library
      shell: bash
      id: build
      run: pnpm build

    - name: Run Unit Tests
      shell: bash
      run: pnpm test
